version: "3.8"

services:
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservice-network 
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - microservice-network  

  configserver:
    image: usmannaveed13/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    
    networks:
      - microservice-network
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/     
      
  eurekaserver:
    image: usmannaveed13/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - microservice-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/        
  accounts:
    image: usmannaveed13/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    
    networks:
      - microservice-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  accounts1:
    image: usmannaveed13/accounts:latest
    mem_limit: 700m
    ports:
      - "8081:8080"
    
    networks:
      - microservice-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka        
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/     
  loans:
    image: usmannaveed13/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
      
    networks:
      - microservice-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka     
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/   
  cards:
    image: usmannaveed13/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    
    networks:
      - microservice-network
    depends_on:
      - configserver
      - eurekaserver  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:  
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  gatewayserver:
    image: usmannaveed13/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"  
    networks:
      - microservice-network
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:  
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
networks:
  microservice-network: 