version: "3.8"

services:
  accounts:
    image: usmannaveed13/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    
    networks:
      - microservice-network
  loans:
    image: usmannaveed13/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
      
    networks:
      - microservice-network
  cards:
    image: usmannaveed13/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    
    networks:
      - microservice-network
  
networks:
  microservice-network: 